language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install argparse unittest2; fi
    - python setup.py --quiet build --build-base=".build-$TRAVIS_PYTHON_VERSION" install

before_script:
    # This is needed for Python multiprocessing.
    # https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

script:
    - python test/test_autopep8.py
    - python test/acid.py -aaa --experimental test/example.py
    - python test/acid.py -aaa --experimental test/example_with_reduce.py

    - if [ "$TRAVIS_PYTHON_VERSION" == "3.3" ]; then python -m doctest -v README.rst; fi

    - if [ "$TRAVIS_PYTHON_VERSION" != "pypy" ]; then pep8 autopep8.py; fi

    - pip --quiet install pydiff
    - python test/acid.py -aaa --compare-bytecode --experimental test/example.py

    - python test/test_suite.py

after_success:
    # pypy is too slow.
    - if [ "$TRAVIS_PYTHON_VERSION" != "pypy" ]; then ./coveralls.bash; fi
